### ISSUE TITLE
Aspose.Slides 15.5.0 vs 15.7.0

### ISSUE THREAD

**Issue by nhojpatrick** [aspose-slides/Aspose.Slides-for-Java#10]
Is there a reason why the examples are using 15.5.0, not something newer like 15.7.0? Just wondering as I thought the examples would keep in sync with development.

**Comment by saqib-razzaq-aspose** [comment]
We keep on updating the examples with the latest release. As Aspose.Slides for Java 15.7.0 is released recently, the examples will be updated in coming days.
