### ISSUE TITLE
aspose java slides repo examples project doesn't compile

### ISSUE THREAD

**Issue by thebitmuncher** [aspose-slides/Aspose.Slides-for-Java#23]
The aspose java slides repo examples project doesn't compile:

[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.941 s
[INFO] Finished at: 2019-03-13T06:17:58-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project slides-java-examples: Compilation failure: Compilation failure: 
[ERROR] /home/chris/codeProjects/Aspose.Slides-for-Java/Examples/src/main/java/com/aspose/slides/examples/Presentation/Conversion/ConvertingPresentationToTIFFWithCustomSize.java:[33,59] unmappable character for encoding UTF8
[ERROR] /home/chris/codeProjects/Aspose.Slides-for-Java/Examples/src/main/java/com/aspose/slides/examples/Slides/Transitions/SetTransitionMorphType.java:[8,25] cannot find symbol
[ERROR]   symbol:   class IMorphTransition
[ERROR]   location: package com.aspose.slides
[ERROR] /home/chris/codeProjects/Aspose.Slides-for-Java/Examples/src/main/java/com/aspose/slides/examples/Slides/Transitions/SetTransitionMorphType.java:[11,25] cannot find symbol
[ERROR]   symbol:   class TransitionMorphType
[ERROR]   location: package com.aspose.slides
[ERROR] /home/chris/codeProjects/Aspose.Slides-for-Java/Examples/src/main/java/com/aspose/slides/examples/Slides/Transitions/SupportOfMorphTransition.java:[39,115] cannot find symbol
[ERROR]   symbol:   variable Morph
[ERROR]   location: class com.aspose.slides.TransitionType
[ERROR] /home/chris/codeProjects/Aspose.Slides-for-Java/Examples/src/main/java/com/aspose/slides/examples/Slides/Transitions/SetTransitionMorphType.java:[29,97] cannot find symbol
[ERROR]   symbol:   variable Morph
[ERROR]   location: class com.aspose.slides.TransitionType
[ERROR] /home/chris/codeProjects/Aspose.Slides-for-Java/Examples/src/main/java/com/aspose/slides/examples/Slides/Transitions/SetTransitionMorphType.java:[30,119] cannot find symbol
[ERROR]   symbol:   variable TransitionMorphType
[ERROR]   location: class com.aspose.slides.examples.Slides.Transitions.SetTransitionMorphType
[ERROR] /home/chris/codeProjects/Aspose.Slides-for-Java/Examples/src/main/java/com/aspose/slides/examples/Slides/Transitions/SetTransitionMorphType.java:[30,15] cannot find symbol
[ERROR]   symbol:   class IMorphTransition
[ERROR]   location: class com.aspose.slides.examples.Slides.Transitions.SetTransitionMorphType
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by mannanfazil** [comment]
@thebitmuncher 
Please download updated pom.xml. All examples are getting compiled successfully now and you may please verify them. If still there is any issue, please feel free to share with us.

**Comment by thebitmuncher** [comment]
Ok I pulled down the latest code and saw that it compiled successfully with maven.  Closing the issue. 
 Thank you
