### ISSUE TITLE
Examples throw NPE when run

### ISSUE THREAD

**Issue by thebitmuncher** [aspose-slides/Aspose.Slides-for-Java#24]
```
Using data directory: C:\Users\me\codeProjects\Aspose.Slides-for-Java\Examples\src\main\resources\com\aspose\slides\examples\Presentation\Creation\CreateAPresentation
Exception in thread "main" java.lang.NullPointerException
	at com.aspose.slides.internal.j1.class.do(Unknown Source)
	at com.aspose.slides.internal.j1.class.new(Unknown Source)
	at com.aspose.slides.internal.j1.class.for(Unknown Source)
	at com.aspose.slides.internal.j1.class.do(Unknown Source)
	at com.aspose.slides.internal.j8.for.do(Unknown Source)
	at com.aspose.slides.internal.ey.long.if(Unknown Source)
	at com.aspose.slides.internal.ey.long.case(Unknown Source)
	at com.aspose.slides.internal.ey.goto.do(Unknown Source)
	at com.aspose.slides.internal.ey.goto.<init>(Unknown Source)
	at com.aspose.slides.internal.ey.goto.<init>(Unknown Source)
	at com.aspose.slides.internal.ey.goto.<init>(Unknown Source)
	at com.aspose.slides.internal.lw.public.do(Unknown Source)
	at com.aspose.slides.ns.do(Unknown Source)
	at com.aspose.slides.ns.do(Unknown Source)
	at com.aspose.slides.ns.do(Unknown Source)
	at com.aspose.slides.ai6.do(Unknown Source)
	at com.aspose.slides.nb.do(Unknown Source)
	at com.aspose.slides.ko.do(Unknown Source)
	at com.aspose.slides.ny.do(Unknown Source)
	at com.aspose.slides.aks.for(Unknown Source)
	at com.aspose.slides.aks.default(Unknown Source)
	at com.aspose.slides.c3.do(Unknown Source)
	at com.aspose.slides.BaseSlide.do(Unknown Source)
	at com.aspose.slides.Slide.do(Unknown Source)
	at com.aspose.slides.Slide.do(Unknown Source)
	at com.aspose.slides.acy.try(Unknown Source)
	at com.aspose.slides.acy.do(Unknown Source)
	at com.aspose.slides.Presentation.do(Unknown Source)
	at com.aspose.slides.Presentation.do(Unknown Source)
	at com.aspose.slides.Presentation.save(Unknown Source)
	at com.aspose.slides.examples.Presentation.Creation.CreateAPresentation.main(CreateAPresentation.java:42)
```

**Comment by mannanfazil** [comment]
@thebitmuncher 
We have tested the issue and its working fine. Please use the latest examples and make sure the required directory exists where you are saving output file. If still, you are facing this issue please let us know.

Please check attached document for your kind reference. [HelloWorld.pptx](https://github.com/aspose-slides/Aspose.Slides-for-Java/files/3012130/HelloWorld.pptx)

**Comment by thebitmuncher** [comment]
Ok - yes I'm using the latest examples and my directory exists.  The pom in the examples is using java version 1.7.    Are they expected to work with newer jdk versions?  I'm using 1.8.

**Comment by mudassirfayyaz** [comment]
@thebitmuncher ,

Aspose.Slides supports Java 6, 7 and 8. In POM the classifier does show jdk16 which actually means to use JAR file that is supported for Java 6 and above. Actually, earlier we had two different Jar files for Java 4,5 and Java 6 onward respectively. I hope the shared elaboration will be helpful.

**Comment by thebitmuncher** [comment]
Ok - I saw someone else having a similar error "Unknown Source" where the aspose dev team replied to the user that they must use a license for it to work.  
https://forum.aspose.com/t/unable-to-convert-html-to-pdf/15014

I'm not using a license.  Is it true that running the examples requires a license?

**Comment by mudassirfayyaz** [comment]
@thebitmuncher ,

The thread that you have referred is related to different API (Aspose.PDF) and also nature of issue reported there is different as well. Can you please share the Operating System and Java details used on your end with us. I also suggest you to please try using following sample code in a new Java application that refer to Aspose.Slides for Java.jar as well.

    public static void CreatePres()
    {
     
        String dataDir = "C:\\";

        // Instantiate Presentation
        com.aspose.slides.Presentation pres = new com.aspose.slides.Presentation();

        // Get the first slide
        com.aspose.slides.ISlide sld = (ISlide) pres.getSlides().get_Item(0);

        // Add an AutoShape of Rectangle type
        com.aspose.slides.IAutoShape ashp = sld.getShapes().addAutoShape(ShapeType.Rectangle, 150, 75, 150, 50);

        // Add ITextFrame to the Rectangle
        ashp.addTextFrame("Hello World");

        // Change the text color to Black (which is White by default)
        ashp.getTextFrame().getParagraphs().get_Item(0).getPortions().get_Item(0).getPortionFormat().getFillFormat()
                        .setFillType(FillType.Solid);
        ashp.getTextFrame().getParagraphs().get_Item(0).getPortions().get_Item(0).getPortionFormat().getFillFormat()
                        .getSolidFillColor().setColor(java.awt.Color.BLACK);

        // Change the line color of the rectangle to White
        ashp.getShapeStyle().getLineColor().setColor(java.awt.Color.WHITE);

        // Remove any fill formatting in the shape
        ashp.getFillFormat().setFillType(FillType.NoFill);

        // Save the presentation to disk
        pres.save(dataDir + "HelloWorld.pptx", com.aspose.slides.SaveFormat.Pptx);
   
    }

**Comment by thebitmuncher** [comment]
I'm using,  Windows 10, Java 1.8, running from eclipse 2018-12.

When I try to run your code saving directly to the C drive - I get this error:

Caused by: java.io.FileNotFoundException: C:\HelloWorld.pptx (Access is denied)

When I specify a different directory in my user home, I get the familiar NPE error:

Exception in thread "main" java.lang.NullPointerException
	at com.aspose.slides.internal.j1.class.do(Unknown Source)
	at com.aspose.slides.internal.j1.class.new(Unknown Source)
	at com.aspose.slides.internal.j1.class.for(Unknown Source)
	at com.aspose.slides.internal.j1.class.do(Unknown Source)
	at com.aspose.slides.internal.j8.for.do(Unknown Source)
	at com.aspose.slides.internal.ey.long.if(Unknown Source)
	at com.aspose.slides.internal.ey.long.case(Unknown Source)
	at com.aspose.slides.internal.ey.goto.do(Unknown Source)
	at com.aspose.slides.internal.ey.goto.<init>(Unknown Source)
	at com.aspose.slides.internal.ey.goto.<init>(Unknown Source)
	at com.aspose.slides.internal.ey.goto.<init>(Unknown Source)
	at com.aspose.slides.internal.lw.public.do(Unknown Source)
	at com.aspose.slides.ns.do(Unknown Source)
	at com.aspose.slides.ns.do(Unknown Source)
	at com.aspose.slides.ns.do(Unknown Source)
	at com.aspose.slides.ai6.do(Unknown Source)
	at com.aspose.slides.nb.do(Unknown Source)
	at com.aspose.slides.ko.do(Unknown Source)
	at com.aspose.slides.ny.do(Unknown Source)
	at com.aspose.slides.aks.for(Unknown Source)
	at com.aspose.slides.aks.default(Unknown Source)
	at com.aspose.slides.c3.do(Unknown Source)
	at com.aspose.slides.BaseSlide.do(Unknown Source)
	at com.aspose.slides.Slide.do(Unknown Source)
	at com.aspose.slides.Slide.do(Unknown Source)
	at com.aspose.slides.acy.try(Unknown Source)
	at com.aspose.slides.acy.do(Unknown Source)
	at com.aspose.slides.Presentation.do(Unknown Source)
	at com.aspose.slides.Presentation.do(Unknown Source)
	at com.aspose.slides.Presentation.save(Unknown Source)
	at org.cr.ppt.CreatePres.createPresTest(CreatePres.java:45)
	at org.cr.ppt.CreatePres.main(CreatePres.java:11)

**Comment by thebitmuncher** [comment]
The NPE error still happens when writing to a ByteArrayOutputStream (only writes to memory and doesn't use the hard drive):

```
	    OutputStream outStream = new ByteArrayOutputStream(); 
	    
	    pres.save(outStream, com.aspose.slides.SaveFormat.Pptx);  // throws same NPE error
```

**Comment by thebitmuncher** [comment]
Here is the simplest example to save a presentation - it still fails with the NPE

```
import java.io.ByteArrayOutputStream;
import java.io.OutputStream;

import com.aspose.slides.Presentation;

public class RealSimple {

	public static void main(String[] args) {

		Presentation pres = new Presentation();

		OutputStream outStream = new ByteArrayOutputStream();

		pres.save(outStream, com.aspose.slides.SaveFormat.Pptx); // fails NPE
	}
}
```

**Comment by mudassirfayyaz** [comment]
@thebitmuncher ,

It's very strange that a basic test is failing on your end. This is certainly some environment issue on your end. Can you please share the Aspose.Slides for Java version being used on your end. Is it possible, if you may please consider testing on a different machine using Aspose.Slides for Java 19.2 and above simplest code.

**Comment by thebitmuncher** [comment]
Hi yes the NPE was happening with Aspose.Slides for Java 19.2.   I did try it on a new, different machine and it worked without the exception.  For the problem machine - I reinstalled jdk 1.8 - and the NPE still happened.

What is the source code looking at on the machine where it's running?  Is it looking to see what operating system it's running on from jvm properties - and then doing certain logic?  When it sees Windows - does it look in the registry?  

For the library that the aspose team uses to obfuscate the jar .class files and sign them to enable enforcing a license - does that library depend on certain machine-specific settings being in place (ie. security encryption certs from the jdk, or creating guids based on the mac address being available)?

In the NPE stack trace on this line - inside the Presentation.java source - what object is it attempting to represent when it says "unknown source"?
com.aspose.slides.Presentation.save(Unknown Source)

**Comment by mudassirfayyaz** [comment]
@thebitmuncher ,

It's good to know that things work on your end using new machine. It is clearly some issue related to Java on your first machine otherwise there is no specific configuration requirement for Aspose.Slides and it is easily used with JDK 1.6, JDK 1.7 and JDK 1.8. We may not consider this to be an issue related to API as you have not been reproduced this as well on secondary machine.

**Comment by thebitmuncher** [comment]
The second new machine starting failing with the same "Unknown Source NPE" and same obfuscated stacktrace that was happening on the first machine.  The second machine was a brand new Windows 10 machine with a fresh install of jdk / jre 1.8 u 192.   

The failure began after about the 20th successful usage of Presentation.save(...).   When the failure happened on this clean new machine, I went to try that very minimal 3-line example referenced in this issue, and saw it was failing also now.  Nothing in that 3-line example has changed.  I ran it about five times and it failed all times.  I cannot save any presentations on the new machine now.  I deleted the aspose jar and pulled it down from the aspose mvn repo again - but got the same failure.  I run from the command line - I'm not going through an IDE.

On the first machine - that NPE started happening after about 10 successful usages.  Since it's happening on the second clean/new machine now - that means this is an issue with the aspose library - not the machine configuration.  

Until this aspose issue is fixed - I would not recommend customers use it in production.  When installed on a server - it's not acceptable for it to work 10-20 times and then begin failing indefinitely. 

The other thread forum where a customer pasted the same stack trace for a "different scenario" - was likely unrelated to the scenario being different - but rather due to the "deployment licensing obfuscation build" aspose uses - which is not reliable.

I believe the issue is - that the aspose library is either itself directly (or indirectly through the "licensing/obfuscation build process" -- depending on certain environment parameters:  ie mac address, serial number, jdk cache, temp files, jdk certs, os certs, win. registry, cached extract, etc.) - performing a change or check, that - when once it goes bad - the aspose library becomes unusable.

I'm requesting that the aspose support team:
* tests enough times until the error is reproduced. 
* Examines their "obfuscation/ licensing" tool and seek support on it being corrected
* Look at the "Presentation.save(...)" code to determine what "Unknown Source" is - and adding a fix

- If support is needed - I would be interested in getting access to the source code and build/deployment script - I would offer to fix it.

**Comment by mudassirfayyaz** [comment]
@thebitmuncher ,

We are sorry for your inconvenience and have read the details provided by you. An issue with ID **SLIDESJAVA-37618** has been added in our issue tracking system with high priority to investigate that why a basis test is getting failed in your environment. I request you to be patient and will share the feedback with you as soon as we will complete our investigation.

**Comment by thebitmuncher** [comment]
Ok thank you - I look forward to an update.  Let me know if I can help test.

**Comment by thebitmuncher** [comment]
Hi I'm checking if there is an update on this issue?  Could it be related to a temp directory that aspose slides java is creating?  How can the temp directory it chooses be found - or configured?

**Comment by mannanfazil** [comment]
@thebitmuncher 
Unfortunately, your issue is not resolved yet. We will inform you via this thread as soon as this issue will be resolved. We apologize for your inconvenience.

**Comment by mannanfazil** [comment]
@thebitmuncher 

We have tested the issue but unable to reproduce this issue on our end. We tried Windows 10 Pro with JDK 1.8 (1.7, 1.6). We tried many times using an administrator account, a guest account and a newly created user account, but everything works fine.
As a workaround of this issue,
•	Please test the scenario on Windows without any installed programs (no antivirus and etc.) except for IDE and JDK
•	We also investigated the provided stack trace and found that the error occurs when the application tries to access the Windows fonts directory. Can you please check the issue with accessing Windows fonts folder?

In case the above workaround does not fix the issue, please share detailed information about Windows (Home? Pro? and etc.), user rights and sample project.

We will further look into the details of this problem and provide you more information. We apologize for your inconvenience.
