### ISSUE TITLE
TIFF files are corrupted when rendering with TiffCompressionTypes.CCITT4

### ISSUE THREAD

**Issue by tmhungcode** [aspose-slides/Aspose.Slides-for-Java#26]
I used this example project, updated the pptx file with my own in **ConvertingPresentationToTIFFWithCustomSize**, and set TiffCompressionTypes.CCITT4.  I attached my pptx file below
The output file was corrupted and couldn't be open with MacOS Previewer. Some other TIFF viewer apps only showed the first image

![image](https://user-images.githubusercontent.com/2813016/82063714-06e4ca80-96f6-11ea-8e00-f922f570b673.png)

[input_4_slides.pptx](https://github.com/aspose-slides/Aspose.Slides-for-Java/files/4635067/4_slides.pptx)
[4_slides.tiff.zip](https://github.com/aspose-slides/Aspose.Slides-for-Java/files/4635078/4_slides.tiff.zip)

**Comment by mudassirfayyaz** [comment]
@tmhung88 ,

We have investigated the issue on our end. It seems to be an issue in API and a ticket with ID SLIDESJAVA-38110 has been created in our issue tracking system to further investigate and resolve the issue. We will share the notification with you once the issue will be resolved.

**Comment by andreypotapovaspose** [comment]
@tmhung88,
The issues you have found earlier (filed as **SLIDESJAVA-38110**) have been fixed in this [update](https://downloads.aspose.com/slides/java/new-releases/aspose.slides-for-java-20.7/). You can use the latest version of [Aspose.Slides](https://downloads.aspose.com/slides/java) already.
